### ISSUE TITLE
What ruby.wasm build does Ruvy use by default?

### ISSUE THREAD

**Issue by Forthoney** [Shopify/ruvy#39]
It's somewhat unclear from the README.md which version Ruvy uses by default - it only mentions how to specify a different version.
My guess is 2.1.0/3_2/wasm32-unknown-wasi/minimal, going off of what the contents of crates/ruby-wasm-assets/src/lib.rs, but explicitly stating it in the docs would be awesome!

**Comment by Forthoney** [comment]
One possibility is to just print the ruby version when invoking the CLI. That way, people have an easy way of knowing what the default settings are + no concerns about documentation going out of date

**Comment by saulecabrera** [comment]
Your suggestion also works, perhaps we could display the (ruby.wasm and ruby) versions when invoking `ruvy --help`, that said, I think this approach serves a different kind of audience: those who already have installed or are willing to install `ruvy`. I suspect that not everyone will want to install `ruvy` only to learn about the default settings, in fact some users might only install it if the default settings meet their needs (and don't want to go through the process of customizing them), so personally, the more I think about this, the more it's clear to me that we could (and probably should) add them in both places (cli + README). 

Would you be willing to work on a PR with your suggestion?

**Comment by saulecabrera** [comment]
https://github.com/Shopify/ruvy/pull/46 addresses this issue.
