### ISSUE TITLE
Using in Shopify Functions

### ISSUE THREAD

**Issue by konung** [Shopify/ruvy#61]
Hello.
Just stumbled across https://shopify.engineering/introducing-ruvy, which lead me to this repo. 

I was wondering if there is an example or doc that explains how to use this with Shopify Functions, or is it not ready yet for that? 

Thank you

**Comment by saulecabrera** [comment]
We added more clarity to answer why Ruvy is not ready to be used with Shopify Functions in https://github.com/Shopify/ruvy/pull/62.

**Comment by saulecabrera** [comment]
There's no roadmap at the moment. But we do accept and encourage contributions from the community if there's interest in making  Ruvy compatible with Shopify Functions. 

We are happy to provide guidance/clarity on investigating any of the items described in https://github.com/Shopify/ruvy?tab=readme-ov-file#compatibility-with-shopify-functions
